### ISSUE TITLE
Mudança na página de visualização do medicamento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#25]
- [x] Eliminar a caixa de composição e ATC e incluir a informação na segunda linha da forma farmaceútica (menu esquerda)
- [x] Eliminar Listas e Listas de países
- [x] Transformar "Observaciones para la forma farmacêutica se encuentra en las listas:" por uma tabela com 3 colunas: Lista | Seção da Lista | Observação. Mudar o título para "Este medicamento está presente em". O nome da lista deve conter o link para a mesma.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/medlist/commit/f7f826be87082ad63a830c83496a94bf30fb8602
