### ISSUE TITLE
Alterar a identidade visual do medlist de acordo com a nova do PRAIS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#3]
Utilizar o mesmo banner da prais, retirando a barra laranja e mantendo o nome Annotated Medicine Lists nos tres idiomas.

**Comment by renatomurasaki** [comment]
Utilizar como cor de fundo o cinza, como a imagem abaixo, e separar o banner das demais partes do site com a barra escura.
![image](https://user-images.githubusercontent.com/1226218/32906133-2c6d7ad6-cae3-11e7-8761-aed7c2bc39a2.png)

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/medlist/commit/3bbc603c0ff2ac6d5c6e4ac1826193e865a697e7
