### ISSUE TITLE
Verificar possíveis vulnerablidades de segurança, conforme mensagem de ITS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#42]
![image](https://user-images.githubusercontent.com/1226218/86279820-070b2d80-bbb1-11ea-9c70-afae9770af4f.png)

**Comment by viniciusandrade** [comment]
Aberto chamado interno (Ocomon 7272) para ajustes em configuração do Apache referente a segurança de acordo com a seguinte referência: https://geekflare.com/http-header-implementation/

**Comment by viniciusandrade** [comment]
Ajustes aplicados na configuração do Apache pela equipe do Instituto Stela com apoio do Marco.
