### ISSUE TITLE
Na pagina de detalhes do medicamento esta sendo apresentado formas farmacêuticas de listas não publicadas

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/medlist#44]
Na seção "Este medicamento esta presente em" também estão sendo apresentados listas não publicadas.

Exemplo:

![erro-medlist](https://user-images.githubusercontent.com/349287/91094632-6f1a4500-e631-11ea-9b48-2011ff59c1ca.jpg)

**Comment by viniciusandrade** [comment]
@renatomurasaki,

Correção realizada e teste efetuado na página:
https://medlistapp.paho.org/es/medicine/261/

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado!
