### ISSUE TITLE
Atualizar iAHx do Medlist para versão mais atual da plataforma

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#45]

**Comment by viniciusandrade** [comment]
@renatomurasaki atualização disponível no ambiente de testes:
 
https://pesquisa.teste.bvsalud.org/medlist/

Falta um pequeno ajuste de CSS na caixa de pesquisa que o Marcio esta verificando. 

Quando possível, favor solicitar a validação e informar se pode ser substituído em produção.

**Comment by renatomurasaki** [comment]
@viniciusandrade algumas observações:

- é possível excluir do cluster Categoria, as entradas que se referem ao primeiro nível da lista dos países, por exemplo, "Essential and Prioritized Medications (378)", "Listado Medicamentos Del Plan Obligatorio De Salud (357)", "Essential Medicines List - Ecuador (350)", "LINAME 2011 - 2013 (337)", "List of Generic Medications - Venezuela (151)", "Ministerio de Salud Pública (58)" etc?
- é possível colocar os nomes das categorias somente com a primeira letra das palavras em maiúsculo ou terá que editar no Django?
- acho melhor alterar o nome do cluster Listas para Listas OPAS/OMS | Listas OPS/OMS | PAHO/WHO Lists, porque os países estão no cluster País

**Comment by viniciusandrade** [comment]
@renatomurasaki sobre as observações:

- De forma simples não é possível uma vez que pelo que verifiquei no código a cada forma farmacêutica é aplicado a seguinte função: ``` section_tree = section.get_ancestors() ``` que retorna todos as seções anteriores. Caso julgue necessário favor abrir novo issue para que eu possa tentar refatorar este código e identificar o primeiro nível.
- Ajuste realizado.
- Ajuste realizado.

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade sobre o item 1, vou abrir novo issue. Sobre o item 2, o cluster Listas OPAS/OMS não pode sofrer o ajuste porque impacta no nome PAHO e WHO que devem ser grafados com maísculas.

**Comment by viniciusandrade** [comment]
@renatomurasaki item 2 alterado para não sofrer o ajuste de formatação.

**Comment by renatomurasaki** [comment]
@viniciusandrade há alguma forma de colocar a primeira letra de todas as palavras de uma string em maiúscula? Se não for possível, teremos que retirar este ajuste no cluster Listas do Países, porque estamos grafando incorretamente os nomes compostos de alguns países, e realizar o ajuste manualmente no Django.

**Comment by viniciusandrade** [comment]
@renatomurasaki existe somente mais um filtro a ser testado que chama-se ucwords  que irá mudar para maiúscula as primeiras palavras. 

Apliquei no ambiente de testes. Caso não fique bom terá que ser alterado manualmente.

**Comment by renatomurasaki** [comment]
@viniciusandrade vai ter que alterar manualmente, pois esta função não identifica stopwords e tokens com caracteres especiais, tipo aspas. Pode retirar este tratamento, por favor.

**Comment by viniciusandrade** [comment]
@renatomurasaki OK, tratamento retirado e issue criado.

**Comment by viniciusandrade** [comment]
@renatomurasaki normalização manual do nome das listas realizada, favor, quando possível verificar se podemos atualizar IAHx do Medlist em produção.

https://pesquisa.teste.bvsalud.org/medlist/
