### ISSUE TITLE
Criar novos parâmetros para comparação de listas de medicamentos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#46]
O mecanismos atual de comparação das listas de medicamentos utiliza 3 parâmetros:

**Princípio Ativo (1)** + **Tipo de Forma Farmacêutica (2)** + **Concentração do princípio ativo (3)**

![image](https://user-images.githubusercontent.com/1226218/108908740-6e736300-7602-11eb-8676-39660d699836.png)

Considerando as limitações dos dados ingressados nas listas que em determinados casos não apresentam dados de forma farmacêutica (atual lista da Argentina) ou utilizam faixa de concentração (mínimo-máximo) do princípio ativo (lista da OMS), facilitará para o usuário se o mecanismo de comparação das listas oferecer a possibilidade de escolher o uso de outros parâmetros de comparação, além dos 3 atuais:

- Comparação com 1 parâmetro: apenas por princípio ativo
- Comparação com 2 parâmetros: princípio ativo + tipo de forma farmacêutica
- Comparação com 3 parâmetros: princípio ativo + tipo de forma farmacêutica + concentração do princípio ativo

**Comment by viniciusandrade** [comment]
@renatomurasaki realizei vários ajustes no código para permitir as comparação parciais indicadas.

Apliquei os ajustes no nosso ambiente de homologação mas a base de dados lá é uma versão bem anterior a da produção.

Quando possível você poderia dar uma olhada inicial para ver se fazem sentido as listagens produzidas pela comparação usando as combinações e listas disponíveis?

https://medlistapp.homolog.bvsalud.org/en/list/compare

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade esse é o comportamento esperado! Obrigado! Pode colocar em produção

**Comment by viniciusandrade** [comment]
Atualizado em produção.
