### ISSUE TITLE
Mensagem de segurança na caixa de busca do Medlist

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#47]
Ao clicar na caixa de busca aparece a seguinte imagem

![image](https://user-images.githubusercontent.com/1226218/109522951-94c75180-7a8d-11eb-991a-2b85d44c5097.png)

Ao realizar a busca, aparece a seguinte tela

![image](https://user-images.githubusercontent.com/1226218/109523079-b4f71080-7a8d-11eb-96e7-2cddda33c8fe.png)

**Comment by marcioalvessilva** [comment]
Tema atualizado e atualizado na homolog - https://medlistportal.homolog.bvsalud.org/

**Comment by viniciusandrade** [comment]
Ajuste aplicado em produção.
