### ISSUE TITLE
Eliminar o primeiro nível da hierarquia das seções das listas de medicamentos quando for gerar as entradas do filtro Categoria

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#48]

**Comment by viniciusandrade** [comment]
@renatomurasaki ajuste realizado e índice regerado, favor quando possível validar:

https://pesquisa.teste.bvsalud.org/medlist/

Obrigado.
Issue relacionado: https://github.com/bireme/medlist/issues/45

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado!
