### ISSUE TITLE
Ao atualizar a versão do iAHx, manter o mesmo breadcrumb com respectivos links atualmente disponível em produção

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#49]
Issue relacionado: #45

**Comment by viniciusandrade** [comment]
@renatomurasaki breadcrumb atualizado no ambiente de testes:

https://pesquisa.teste.bvsalud.org/medlist/

**Comment by renatomurasaki** [comment]
@viniciusandrade validado! obrigado
