### ISSUE TITLE
Erro na comparação de listas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#5]
Ao acessar http://medlist.paho.org/list/compare, dá erro

`IOError at /list/compare
Directory /home/aplicacoes/medlist/medlist/index does not exist`

**Comment by viniciusandrade** [comment]
@renatomurasaki,

Foi restaurado do backup do servidor do Canadá o diretório apontado no erro pois nossa instância não possuía este diretório. Quando possível favor verificar.

[]s

**Comment by renatomurasaki** [comment]
@viniciusandrade agora está funcionando perfeitamente. Obrigado
