### ISSUE TITLE
Melhorar visualização das listas para realizar a comparação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#53]
![image](https://user-images.githubusercontent.com/1226218/111791699-375f3d00-88a2-11eb-96ab-85a4130da512.png)

Seria possível duas listas suspensas, uma para Lists e outra para Countries, com múltipla seleção, algo semelhante com o comportamento abaixo (no caso do Medlist não teria a opção Tudo e por padrão nenhum país ou lista estaria selecionado)

![image](https://user-images.githubusercontent.com/1226218/111792132-b5bbdf00-88a2-11eb-90f5-d957c89979a8.png)

Também mostrar as listas em ordem alfabética.

**Comment by viniciusandrade** [comment]
@renatomurasaki, acredito que sim ... vou tentar aplicar o mesmo componente usado no FI-ADMIN para as listas controladas de múltipla seleção.

**Comment by viniciusandrade** [comment]
@renatomurasaki componente JS de múltipla seleção integrado na página de comparação de listas, quando possível favor validar:

https://medlistapp.paho.org/en/list/compare

Obrigado.

**Comment by renatomurasaki** [comment]
Excelente, @viniciusandrade ! Pode aplicar na produção

**Comment by viniciusandrade** [comment]
Atualizado em produção.
