### ISSUE TITLE
Medicamento comum em diferentes listas não aparece no momento da comparação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#54]
O medicamento abaixo está em diversas listas, como podemos notar na imagem abaixo
![image](https://user-images.githubusercontent.com/1226218/111793520-1e578b80-88a4-11eb-8b15-380cc7f3e822.png)

Ao fazer a comparação entre as listas da Argentina e da Colombia, o sistema não mostra qualquer medicamento

![image](https://user-images.githubusercontent.com/1226218/111793937-83ab7c80-88a4-11eb-911e-1aa953fd0b36.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki, processo de geração da estrutra que permite a comparação de listas finalizou após aproximadamente 7 horas.

Quando possível, favor realizar uma nova verificação.

Obrigado

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado! Com o término do processamento, a comparação funcionou!
