### ISSUE TITLE
Ordenar o resultado da comparação de listas por ordem alfabética do nome do medicamento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#55]

**Comment by viniciusandrade** [comment]
@renatomurasaki ajuste realizado, quando possível favor validar:

https://medlistapp.paho.org/en/list/compare

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado! Pode aplicar em produção

**Comment by viniciusandrade** [comment]
Atualizado em produção.
