### ISSUE TITLE
Erro no link de detalhamento do medicamento recuperado na interface de busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#56]
Exemplo:
1) Buscar aciclovir
![image](https://user-images.githubusercontent.com/1226218/113618155-a623f080-962d-11eb-8d6b-6a479b53265d.png)
2) Clicar no link na palavra aciclovir
https://pesquisa.bvsalud.org/medlist/resource/en/119
![image](https://user-images.githubusercontent.com/1226218/113618275-d10e4480-962d-11eb-83d5-04a1f24e5ed0.png)

O link deve ir para a aplicação do medlist e não no detalhamento padrão do iAHx, ou seja:

https://medlistapp.paho.org/en/medicine/119/

**Comment by viniciusandrade** [comment]
Correção realizada no template e ambiente de produção atualizado.
