### ISSUE TITLE
Apresentar as formas farmaceuticas de um medicamento no resultado de busca em ordem alfabética

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#57]
![image](https://user-images.githubusercontent.com/1226218/113751978-dc6f7780-96e2-11eb-9ebe-d87c132c5d75.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki ajuste realizado no template da pesquisa.
Exemplo:
https://search.bvsalud.org/medlist/?q=aciclovir&where=MEDICINES
