### ISSUE TITLE
Apresentar as formas farmacêuticas em ordem alfabética na página de detalhe do medicamento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#58]
![image](https://user-images.githubusercontent.com/1226218/113752244-1c365f00-96e3-11eb-949a-5d1efd98a6fe.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki ajuste implementado e disponível em produção.
Exemplo:

https://medlistapp.paho.org/en/medicine/119/
