### ISSUE TITLE
Apresentar os medicamentos em ordem alfabética, dentro das seções das listas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/medlist#59]
![image](https://user-images.githubusercontent.com/1226218/113755527-cc599700-96e6-11eb-8a77-45b115c001d6.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki neste nível do template de apresentação não consegui aplicar o ordenamento completo, que leva em consideração as possíveis traduções de um medicamento, assim como eu implementei na página de detalhes e também na busca, pois demandaria muito refatoramento do código.

Neste caso tiver que aplicar a ordenação mais simples que acredito atenderia 90% das listas ficando alguns poucos casos fora de ordem. 

Apliquei esta alteração na produção, favor, quando possível verificar se esta de acordo com esta abordagem ou se devo proceder com a refatoração do código para atender 100% dos casos.

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade considerando apenas o nome do princípio ativo, as listas que vi estão ok com a ordenação. Percebi que não há uma ordem combinando nome do princípio ativo e a forma farmacêutica para os casos que há diversas formas para a mesma droga, mas do jeito que está, para mim, é suficiente para melhorar a experiência do usuário. Antes a leitura estava difícil considerando a falta de ordem alfabética do princípio ativo. Obrigado!
